services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blpss_docker_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
      - minio
    networks:
      - app-network
    volumes:
      - ./data:/app/data

  db:
    image: postgres:16
    container_name: blps_lab2-db
    environment:
      POSTGRES_DB: blpss_docker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MAX_CONNECTIONS: "300"
      PGDATA: /var/lib/postgresql/data/pgdata
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESSKEY: admin
      MINIO_SECRETKEY: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/minio
    command: server ~/minio --console-address :9090
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  app-network:
    driver: bridge