spring.application.name=blps_lab2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/blpss_docker_db
spring.datasource.username=root
spring.datasource.password=root
minio.root.user=hoty
minio.root.password=hoty1337

xmpp.host=localhost
xmpp.domain=localhost
xmpp.port=61222
xmpp.user=admin
xmpp.nickname=spring
xmpp.password=admin

users.file.path=data/users.xml

minio.publicUrl=http://91.204.74.183:9000/
minio.endpoint=http://91.204.74.183:9000

token.signing.key=Q29tcGxleFZlcnlTZWNyZXRLZXlGb3JKV1Q=Q29tcGxleFZlcnlTZWNyZXRLZXlGb3JKV1Q=

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB
server.tomcat.max-swallow-size=150MB

springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security=DEBUG
logging.level.com.atomikos=DEBUG
logging.level.com.atomikos.jdbc=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.camunda.bpm.webapp=DEBUG
camunda.bpm.webapp.csrf-prevention-enabled=true
camunda.bpm.webapp.csrf-prevention-ignore-file-extensions=css,js,map,woff,woff2,ttf,otf,png,svg

spring.quartz.auto-startup=false

camunda.bpm.database.type=postgres
camunda.bpm.database.schema-update=true
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.admin-user.firstName=Admin
camunda.bpm.default-serialization-format=application/json
camunda.bpm.history-level=full
camunda.bpm.job-execution.enabled=true
camunda.bpm.deployment-resource-pattern=classpath*:/processes/**/*.bpmn, classpath*:/forms/**/*.form
camunda.bpm.generic-properties.properties.historyTimeToLive=180
camunda.bpm.generic-properties.properties.enforceHistoryTimeToLive=true